import Page from "./page.js";
export const metadata = {
  title: "WellShop",
  description: "Generated by Next.js",
};
export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Page></Page>
      </body>
    </html>
  );
}
