import "@/Styles/global.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bodyOa">{children}</div>
      </body>
    </html>
  );
}
